/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whoami */
        get: operations["whoami_auth_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tenants */
        get: operations["list_tenants_tenants__get"];
        put?: never;
        /** Create Tenant */
        post: operations["create_tenant_tenants__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Tenant */
        get: operations["get_my_tenant_tenants_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Tenant */
        patch: operations["update_tenant_tenants__tenant_id__patch"];
        trace?: never;
    };
    "/merchants/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Merchants */
        get: operations["list_merchants_merchants__get"];
        put?: never;
        /** Create Merchant */
        post: operations["create_merchant_merchants__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchants/{merchant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Merchant */
        get: operations["get_merchant_merchants__merchant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Merchant */
        patch: operations["update_merchant_merchants__merchant_id__patch"];
        trace?: never;
    };
    "/merchants/{merchant_id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suspend Merchant */
        post: operations["suspend_merchant_merchants__merchant_id__suspend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchants/{merchant_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Merchant */
        post: operations["resume_merchant_merchants__merchant_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_users__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite User */
        post: operations["invite_user_users_invite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bot-config/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_bot_config_templates_get"];
        put?: never;
        /** Create Template */
        post: operations["create_template_bot_config_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bot-config/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Template */
        put: operations["update_template_bot_config_templates__template_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bot-config/{merchant_id}/resolved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolved Config */
        get: operations["resolved_config_bot_config__merchant_id__resolved_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bot-config/{merchant_id}/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Overrides */
        put: operations["update_overrides_bot_config__merchant_id__overrides_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-base/{merchant_id}/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Docs */
        get: operations["list_docs_knowledge_base__merchant_id__docs_get"];
        put?: never;
        /** Create Doc */
        post: operations["create_doc_knowledge_base__merchant_id__docs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-base/{merchant_id}/docs/{doc_id}/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reindex */
        post: operations["reindex_knowledge_base__merchant_id__docs__doc_id__reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description Kept for parity — frontend usually reads conversations directly via Supabase client.
         */
        get: operations["list_conversations_conversations__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/merchant/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Merchant Kpis */
        get: operations["merchant_kpis_analytics_merchant_kpis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/agency/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agency Kpis */
        get: operations["agency_kpis_analytics_agency_kpis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Export */
        post: operations["request_export_analytics_exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playground/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Playground Turn
         * @description UC-08 — sandbox turn. No side-effects: no WhatsApp send, no DB persist.
         */
        post: operations["playground_turn_playground_turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ab-test/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Experiments */
        get: operations["list_experiments_ab_test__get"];
        put?: never;
        /** Create Experiment */
        post: operations["create_experiment_ab_test__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ab-test/{experiment_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Experiment */
        post: operations["start_experiment_ab_test__experiment_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ab-test/{experiment_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Experiment Metrics */
        get: operations["experiment_metrics_ab_test__experiment_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/objections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Objection Report */
        get: operations["objection_report_reports_objections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/objections/extract/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Extraction
         * @description Manually re-run objection extraction for a conversation. Useful during tuning.
         */
        post: operations["trigger_extraction_reports_objections_extract__conversation_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/ghl/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ghl Oauth Start */
        post: operations["ghl_oauth_start_integrations_ghl_oauth_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/ghl/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ghl Oauth Callback */
        get: operations["ghl_oauth_callback_integrations_ghl_oauth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/whatsapp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Whatsapp Verify */
        post: operations["whatsapp_verify_integrations_whatsapp_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Integration Status */
        get: operations["integration_status_integrations_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/whatsapp/{phone_number_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whatsapp Verify
         * @description Meta verification challenge — echo hub.challenge iff verify_token matches.
         */
        get: operations["whatsapp_verify_webhooks_whatsapp__phone_number_id__get"];
        put?: never;
        /** Whatsapp Inbound */
        post: operations["whatsapp_inbound_webhooks_whatsapp__phone_number_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/ghl/{merchant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ghl Inbound */
        post: operations["ghl_inbound_webhooks_ghl__merchant_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ABTestConfig */
        ABTestConfig: {
            /** Default Split */
            default_split?: number[];
            /**
             * Min Sample
             * @default 100
             */
            min_sample: number;
        };
        /** AgencyKpisOut */
        AgencyKpisOut: {
            /** Leads Total */
            leads_total: number;
            /** Active Merchants */
            active_merchants: number;
            /** Messages Received */
            messages_received: number;
            /** Bookings Created */
            bookings_created: number;
            /** Reminders Sent */
            reminders_sent: number;
            /** Merchants Ranking */
            merchants_ranking: {
                [key: string]: unknown;
            }[];
        };
        /** BookingConfig */
        BookingConfig: {
            /** Default Calendar Id */
            default_calendar_id?: string | null;
            /**
             * Default Duration Min
             * @default 30
             */
            default_duration_min: number;
            /**
             * Lookahead Days
             * @default 14
             */
            lookahead_days: number;
        };
        /**
         * BotConfigSchema
         * @description Typed view over the JSONB override bag — validated at write time.
         */
        BotConfigSchema: {
            no_answer?: components["schemas"]["NoAnswerConfig"];
            reactivation?: components["schemas"]["ReactivationConfig"];
            pipeline?: components["schemas"]["PipelineConfig"];
            scoring?: components["schemas"]["ScoringConfig"];
            ab_test?: components["schemas"]["ABTestConfig"];
            schedule?: components["schemas"]["ScheduleConfig"];
            rag?: components["schemas"]["RagConfig"];
            bot?: components["schemas"]["BotSurfaceConfig"];
            escalation?: components["schemas"]["EscalationConfig"];
            privacy?: components["schemas"]["PrivacyConfig"];
            booking?: components["schemas"]["BookingConfig"];
        };
        /** BotSurfaceConfig */
        BotSurfaceConfig: {
            /**
             * Language
             * @default it
             */
            language: string;
            /**
             * Tone
             * @default professionale-amichevole
             */
            tone: string;
        };
        /** EscalationConfig */
        EscalationConfig: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** ExperimentIn */
        ExperimentIn: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Variants */
            variants: components["schemas"]["VariantIn"][];
            /** Primary Metric */
            primary_metric: string;
            /**
             * Min Sample Size
             * @default 100
             */
            min_sample_size: number;
        };
        /** ExperimentOut */
        ExperimentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Status */
            status: string;
            /** Variants */
            variants: {
                [key: string]: unknown;
            }[];
            /** Primary Metric */
            primary_metric: string;
            /** Min Sample Size */
            min_sample_size: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InviteIn */
        InviteIn: {
            /** Email */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "agency_admin" | "agency_user" | "merchant_admin" | "merchant_user";
            /** Merchant Id */
            merchant_id?: string | null;
            /** Full Name */
            full_name?: string | null;
            /** Redirect To */
            redirect_to?: string | null;
        };
        /** KbDocIn */
        KbDocIn: {
            /** Title */
            title: string;
            /**
             * Source
             * @enum {string}
             */
            source: "pdf" | "docx" | "url" | "txt";
            /** Storage Path */
            storage_path?: string | null;
            /** Url */
            url?: string | null;
        };
        /** KbDocOut */
        KbDocOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Chunk Count */
            chunk_count: number;
        };
        /** MerchantIn */
        MerchantIn: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /**
             * Timezone
             * @default Europe/Rome
             */
            timezone: string;
            /**
             * Locale
             * @default it
             */
            locale: string;
        };
        /** MerchantKpisOut */
        MerchantKpisOut: {
            /** Leads Total */
            leads_total: number;
            /** Leads Hot */
            leads_hot: number;
            /** Messages Received */
            messages_received: number;
            /** Messages Replied */
            messages_replied: number;
            /** Response Rate */
            response_rate: number;
            /** Bookings Created */
            bookings_created: number;
            /** Booking Rate */
            booking_rate: number;
            /** Reminders Sent */
            reminders_sent: number;
            /** Score Distribution */
            score_distribution: {
                [key: string]: number;
            }[];
        };
        /** MerchantOut */
        MerchantOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Timezone */
            timezone: string;
            /** Locale */
            locale: string;
        };
        /** MerchantPatch */
        MerchantPatch: {
            /** Name */
            name?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Locale */
            locale?: string | null;
        };
        /** NoAnswerConfig */
        NoAnswerConfig: {
            /**
             * First Reminder Min
             * @default 120
             */
            first_reminder_min: number;
            /**
             * Second Reminder Min
             * @default 1440
             */
            second_reminder_min: number;
            /**
             * Max Followups
             * @default 2
             */
            max_followups: number;
        };
        /** OverridesIn */
        OverridesIn: {
            /** Overrides */
            overrides: {
                [key: string]: unknown;
            };
        };
        /** PipelineConfig */
        PipelineConfig: {
            /**
             * Advance Threshold
             * @default 60
             */
            advance_threshold: number;
            /** Qualified Stage Id */
            qualified_stage_id?: string | null;
        };
        /** PlaygroundMessageIn */
        PlaygroundMessageIn: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /** PlaygroundTurnIn */
        PlaygroundTurnIn: {
            /** System Prompt */
            system_prompt: string;
            /**
             * History
             * @default []
             */
            history: components["schemas"]["PlaygroundMessageIn"][];
            /** User Message */
            user_message: string;
            /** Variant Id */
            variant_id?: string | null;
            /**
             * Use Kb
             * @default true
             */
            use_kb: boolean;
        };
        /** PlaygroundTurnOut */
        PlaygroundTurnOut: {
            /** Reply Text */
            reply_text: string;
            /** Actions */
            actions: {
                [key: string]: unknown;
            }[];
            /** Model */
            model: string;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Latency Ms */
            latency_ms: number;
            /** Retrieved Chunks */
            retrieved_chunks: {
                [key: string]: unknown;
            }[];
        };
        /** PrivacyConfig */
        PrivacyConfig: {
            /**
             * Retention Months
             * @default 24
             */
            retention_months: number;
        };
        /** RagConfig */
        RagConfig: {
            /**
             * Top K
             * @default 5
             */
            top_k: number;
            /**
             * Min Score
             * @default 0.7
             */
            min_score: number;
        };
        /** ReactivationConfig */
        ReactivationConfig: {
            /**
             * Dormant Days
             * @default 90
             */
            dormant_days: number;
            /**
             * Interval Days
             * @default 7
             */
            interval_days: number;
            /**
             * Max Attempts
             * @default 3
             */
            max_attempts: number;
        };
        /** ScheduleConfig */
        ScheduleConfig: {
            /**
             * Active Hours
             * @default 24/7
             */
            active_hours: string;
            /**
             * Off Hours Message
             * @default Grazie per averci contattato! Ti risponderemo al più presto.
             */
            off_hours_message: string;
            /**
             * Timezone
             * @default Europe/Rome
             */
            timezone: string;
        };
        /** ScoringConfig */
        ScoringConfig: {
            /**
             * Hot Threshold
             * @default 80
             */
            hot_threshold: number;
            /**
             * Cold Threshold
             * @default 30
             */
            cold_threshold: number;
        };
        /** TemplateIn */
        TemplateIn: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Defaults */
            defaults: {
                [key: string]: unknown;
            };
            /**
             * Locked Keys
             * @default []
             */
            locked_keys: string[];
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
        };
        /** TemplateOut */
        TemplateOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Defaults */
            defaults: {
                [key: string]: unknown;
            };
            /** Locked Keys */
            locked_keys: string[];
            /** Is Default */
            is_default: boolean;
        };
        /** TenantOut */
        TenantOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
        };
        /** TenantUpdate */
        TenantUpdate: {
            /** Name */
            name?: string | null;
            /** Settings */
            settings?: {
                [key: string]: unknown;
            } | null;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Merchant Id */
            merchant_id: string | null;
            /** Role */
            role: string;
            /** Full Name */
            full_name: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VariantIn */
        VariantIn: {
            /** Id */
            id: string;
            /** Weight */
            weight: number;
            /** Prompt Template Id */
            prompt_template_id?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    whoami_auth_whoami_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tenants_tenants__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tenant_tenants__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_tenant_tenants_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tenant_tenants__tenant_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_merchants_merchants__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_merchant_merchants__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MerchantIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_merchant_merchants__merchant_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_merchant_merchants__merchant_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MerchantPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suspend_merchant_merchants__merchant_id__suspend_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_merchant_merchants__merchant_id__resume_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_users__get: {
        parameters: {
            query?: {
                /** @description Filter users by merchant_id */
                merchant_id?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_user_users_invite_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_bot_config_templates_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_template_bot_config_templates_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_template_bot_config_templates__template_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolved_config_bot_config__merchant_id__resolved_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotConfigSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_overrides_bot_config__merchant_id__overrides_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverridesIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_docs_knowledge_base__merchant_id__docs_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KbDocOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_doc_knowledge_base__merchant_id__docs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KbDocIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KbDocOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_knowledge_base__merchant_id__docs__doc_id__reindex_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                merchant_id: string;
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_conversations__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merchant_kpis_analytics_merchant_kpis_get: {
        parameters: {
            query?: {
                since_days?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantKpisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agency_kpis_analytics_agency_kpis_get: {
        parameters: {
            query?: {
                since_days?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgencyKpisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_export_analytics_exports_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    playground_turn_playground_turn_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaygroundTurnIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaygroundTurnOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_experiments_ab_test__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_experiment_ab_test__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_experiment_ab_test__experiment_id__start_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    experiment_metrics_ab_test__experiment_id__metrics_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    objection_report_reports_objections_get: {
        parameters: {
            query?: {
                since_days?: number;
                samples_per_category?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_extraction_reports_objections_extract__conversation_id__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ghl_oauth_start_integrations_ghl_oauth_start_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ghl_oauth_callback_integrations_ghl_oauth_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whatsapp_verify_integrations_whatsapp_verify_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    integration_status_integrations_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whatsapp_verify_webhooks_whatsapp__phone_number_id__get: {
        parameters: {
            query?: {
                hub_mode?: string;
                hub_challenge?: string;
                hub_verify_token?: string;
            };
            header?: never;
            path: {
                phone_number_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whatsapp_inbound_webhooks_whatsapp__phone_number_id__post: {
        parameters: {
            query?: never;
            header?: {
                "x-hub-signature-256"?: string;
            };
            path: {
                phone_number_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ghl_inbound_webhooks_ghl__merchant_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
export enum ApiPaths {
    health_health_get = "/health",
    whoami_auth_whoami_get = "/auth/whoami",
    list_tenants_tenants__get = "/tenants/",
    create_tenant_tenants__post = "/tenants/",
    get_my_tenant_tenants_me_get = "/tenants/me",
    update_tenant_tenants__tenant_id__patch = "/tenants/{tenant_id}",
    list_merchants_merchants__get = "/merchants/",
    create_merchant_merchants__post = "/merchants/",
    get_merchant_merchants__merchant_id__get = "/merchants/{merchant_id}",
    update_merchant_merchants__merchant_id__patch = "/merchants/{merchant_id}",
    suspend_merchant_merchants__merchant_id__suspend_post = "/merchants/{merchant_id}/suspend",
    resume_merchant_merchants__merchant_id__resume_post = "/merchants/{merchant_id}/resume",
    list_users_users__get = "/users/",
    invite_user_users_invite_post = "/users/invite",
    list_templates_bot_config_templates_get = "/bot-config/templates",
    create_template_bot_config_templates_post = "/bot-config/templates",
    update_template_bot_config_templates__template_id__put = "/bot-config/templates/{template_id}",
    resolved_config_bot_config__merchant_id__resolved_get = "/bot-config/{merchant_id}/resolved",
    update_overrides_bot_config__merchant_id__overrides_put = "/bot-config/{merchant_id}/overrides",
    create_doc_knowledge_base__merchant_id__docs_post = "/knowledge-base/{merchant_id}/docs",
    list_docs_knowledge_base__merchant_id__docs_get = "/knowledge-base/{merchant_id}/docs",
    reindex_knowledge_base__merchant_id__docs__doc_id__reindex_post = "/knowledge-base/{merchant_id}/docs/{doc_id}/reindex",
    list_conversations_conversations__get = "/conversations/",
    get_conversation_conversations__conversation_id__get = "/conversations/{conversation_id}",
    merchant_kpis_analytics_merchant_kpis_get = "/analytics/merchant/kpis",
    agency_kpis_analytics_agency_kpis_get = "/analytics/agency/kpis",
    request_export_analytics_exports_post = "/analytics/exports",
    playground_turn_playground_turn_post = "/playground/turn",
    list_experiments_ab_test__get = "/ab-test/",
    create_experiment_ab_test__post = "/ab-test/",
    start_experiment_ab_test__experiment_id__start_post = "/ab-test/{experiment_id}/start",
    experiment_metrics_ab_test__experiment_id__metrics_get = "/ab-test/{experiment_id}/metrics",
    objection_report_reports_objections_get = "/reports/objections",
    trigger_extraction_reports_objections_extract__conversation_id__post = "/reports/objections/extract/{conversation_id}",
    ghl_oauth_start_integrations_ghl_oauth_start_post = "/integrations/ghl/oauth/start",
    ghl_oauth_callback_integrations_ghl_oauth_callback_get = "/integrations/ghl/oauth/callback",
    whatsapp_verify_integrations_whatsapp_verify_post = "/integrations/whatsapp/verify",
    integration_status_integrations_status_get = "/integrations/status",
    whatsapp_verify_webhooks_whatsapp__phone_number_id__get = "/webhooks/whatsapp/{phone_number_id}",
    whatsapp_inbound_webhooks_whatsapp__phone_number_id__post = "/webhooks/whatsapp/{phone_number_id}",
    ghl_inbound_webhooks_ghl__merchant_id__post = "/webhooks/ghl/{merchant_id}"
}
